Repository MrsSbr/amm-java-9-91-2024, pull requests merged in 2024-12, with the labels that each got.

#194 Nelezin oleg lab6
  app/G9/nelezin.oleg/lab6/build.gradle.kts
  app/G9/nelezin.oleg/lab6/src/main/java/ru/vsu/amm/java/SmokingApplication.java
  app/G9/nelezin.oleg/lab6/src/main/java/ru/vsu/amm/java/classes/Barman.java
  app/G9/nelezin.oleg/lab6/src/main/java/ru/vsu/amm/java/classes/Smoker.java
  app/G9/nelezin.oleg/lab6/src/main/java/ru/vsu/amm/java/classes/Table.java
  app/G9/nelezin.oleg/lab6/src/main/java/ru/vsu/amm/java/enums/Component.java
  settings.gradle.kts
Labels: (x_x)

#191 lab4_jewelry_popova
  app/G91/popova.anastasia/lab1/TaskMagicSquaresInGrid.txt
  app/G91/popova.anastasia/lab2/TaskPlants.txt
  app/G91/popova.anastasia/lab3/TaskAirport.txt
  app/G91/popova.anastasia/lab4/build.gradle.kts
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/Main.java
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/analyzer/SalesAnalyzer.java
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/entity/SaleRecord.java
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/enums/Gemstone.java
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/enums/Jewelry.java
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/enums/PreciousMetal.java
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/util/FileHandle.java
  app/G91/popova.anastasia/lab4/src/main/java/ru/vsu/amm/java/util/SaleFactory.java
  app/G91/popova.anastasia/lab4/src/test/java/ru/vsu/amm/java/SaleRecordTests.java
  settings.gradle.kts
Labels: ฅ^•ﻌ•^ฅ

#228 lab4 done
  app/G9/barbashina.irina/lab4/build.gradle.kts
  app/G9/barbashina.irina/lab4/plant_diary.txt
  app/G9/barbashina.irina/lab4/src/main/java/ru/vsu/amm/java/PlantApplication.java
  app/G9/barbashina.irina/lab4/src/main/java/ru/vsu/amm/java/entity/PlantRecord.java
  app/G9/barbashina.irina/lab4/src/main/java/ru/vsu/amm/java/enums/FertilizerBrand.java
  app/G9/barbashina.irina/lab4/src/main/java/ru/vsu/amm/java/enums/Plant.java
  app/G9/barbashina.irina/lab4/src/main/java/ru/vsu/amm/java/fortests/GetSomePlantRecords.java
  app/G9/barbashina.irina/lab4/src/main/java/ru/vsu/amm/java/service/PlantDiaryAnalysis.java
  app/G9/barbashina.irina/lab4/src/main/java/ru/vsu/amm/java/util/PlantDiaryProcessor.java
  app/G9/barbashina.irina/lab4/src/test/java/ru/vsu/amm/java/PlantDiaryAnalysisTest.java
  app/G9/barbashina.irina/lab4/src/test/java/ru/vsu/amm/java/PlantDiaryProcessorTest.java
  settings.gradle.kts
Labels: ʕ·ᴥ·ʔ

#218 Added Enokyan's lab6
  app/G91/enokyan.gera/lab5/build.gradle.kts
  app/G91/enokyan.gera/lab6/build.gradle.kts
  app/G91/enokyan.gera/lab6/src/main/java/ru/vsu/amm/java/DiningPhilosophers.java
  app/G91/enokyan.gera/lab6/src/main/java/ru/vsu/amm/java/classes/Fork.java
  app/G91/enokyan.gera/lab6/src/main/java/ru/vsu/amm/java/classes/Philosopher.java
  app/G91/enokyan.gera/lab6/src/main/java/ru/vsu/amm/java/classes/Plate.java
  app/G91/enokyan.gera/lab6/src/main/java/ru/vsu/amm/java/classes/Table.java
  settings.gradle.kts
Labels: ʕ·ᴥ·ʔ
