Repository MrsSbr/amm-java-9-91-2024, pull requests merged in 2024-10, with the labels that each got.

#125 Added Enokyan's lab4
  app/G91/enokyan.gera/lab4/TaskGamer.txt
  app/G91/enokyan.gera/lab4/build.gradle.kts
  app/G91/enokyan.gera/lab4/src/main/java/ru/vsu/amm/java/GameWalkthroughDemo.java
  app/G91/enokyan.gera/lab4/src/main/java/ru/vsu/amm/java/entity/GameWalkthrough.java
  app/G91/enokyan.gera/lab4/src/main/java/ru/vsu/amm/java/enums/Genre.java
  app/G91/enokyan.gera/lab4/src/main/java/ru/vsu/amm/java/enums/Rating.java
  app/G91/enokyan.gera/lab4/src/main/java/ru/vsu/amm/java/service/GameWalkthroughStatsService.java
  app/G91/enokyan.gera/lab4/src/main/java/ru/vsu/amm/java/util/FileWorker.java
  app/G91/enokyan.gera/lab4/src/main/java/ru/vsu/amm/java/util/GameWalkthroughFactory.java
  app/G91/enokyan.gera/lab4/src/test/java/ru/vsu/amm/java/GameWalkthroughTests.java
  settings.gradle.kts
Labels: enhancement, help wanted, question

#137 anikandrov andrey lab2_2
  app/G9/anikandrov.andrey/lab2/build.gradle.kts
  app/G9/anikandrov.andrey/lab2/src/main/java/ru/vsu/amm/java/Aircraft.java
  app/G9/anikandrov.andrey/lab2/src/main/java/ru/vsu/amm/java/Airplains.java
  app/G9/anikandrov.andrey/lab2/src/main/java/ru/vsu/amm/java/Bomber.java
  app/G9/anikandrov.andrey/lab2/src/main/java/ru/vsu/amm/java/Fighter.java
  app/G9/anikandrov.andrey/lab2/src/main/java/ru/vsu/amm/java/MilitaryAircraft.java
  app/G9/anikandrov.andrey/lab2/src/main/java/ru/vsu/amm/java/Spy.java
Labels: Исправлены замечания

#113 em_vera_lab2
  app/G91/em.vera/lab1/TaskWateringPlants.txt
  app/G91/em.vera/lab2/TaskFishTank.txt
  app/G91/em.vera/lab2/build.gradle.kts
  app/G91/em.vera/lab2/src/main/java/ru/vsu/amm/java/BettaFish.java
  app/G91/em.vera/lab2/src/main/java/ru/vsu/amm/java/BlowFish.java
  app/G91/em.vera/lab2/src/main/java/ru/vsu/amm/java/Fish.java
  app/G91/em.vera/lab2/src/main/java/ru/vsu/amm/java/Main.java
  app/G91/em.vera/lab2/src/main/java/ru/vsu/amm/java/WaterFowlable.java
  settings.gradle.kts
Labels: Исправила ошибки
