Repository MrsSbr/amm-java-9-91-2024, pull requests merged in 2024-11, with the labels that each got.

#123 chzhan_ira_laba_2
  app/G91/chzhan.ira/lab2/build.gradle.kts
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/ClothingTask.java
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/abstracts/Clothes.java
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/classes/Dress.java
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/classes/Pants.java
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/classes/Shirt.java
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/enums/DressLength.java
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/enums/Size.java
  app/G91/chzhan.ira/lab2/src/main/java/ru/vsu/amm/java/interfaces/Wearable.java
  settings.gradle.kts
Labels: Исправлено

#146 Nelezin Oleg lab5
  app/G9/nelezin.oleg/lab5/build.gradle.kts
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/ReflectionApplication.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/annotation/Autowired.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/annotation/Component.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/configuration/Context.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/service/ComponentScanningService.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/service/FirstService.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/service/SecondService.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/service/impl/ComponentScanningServiceImpl.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/service/impl/FirstServiceImpl.java
  app/G9/nelezin.oleg/lab5/src/main/java/ru/vsu/amm/java/service/impl/SecondServiceImpl.java
  app/G9/nelezin.oleg/lab5/src/test/java/ContextTest.java
  settings.gradle.kts
Labels: ヽ(*・ω・)ﾉ, ＼(＾▽＾)／, (￣ω￣), ٩(◕‿◕)۶

#170 Added Enokyan's lab5
  app/G91/enokyan.gera/lab5/src/main/java/ru/vsu/amm/java/ConfigDemo.java
  app/G91/enokyan.gera/lab5/src/main/java/ru/vsu/amm/java/annotation/Config.java
  app/G91/enokyan.gera/lab5/src/main/java/ru/vsu/amm/java/annotation/Property.java
  app/G91/enokyan.gera/lab5/src/main/java/ru/vsu/amm/java/config/sample.properties
  app/G91/enokyan.gera/lab5/src/main/java/ru/vsu/amm/java/enums/MyColor.java
  app/G91/enokyan.gera/lab5/src/main/java/ru/vsu/amm/java/service/ConfigService.java
  app/G91/enokyan.gera/lab5/src/main/java/ru/vsu/amm/java/service/SampleConfig.java
  app/G91/enokyan.gera/lab5/src/test/java/ru/vsu/amm/java/ConfigTests.java
  app/G91/enokyan.gera/lab5/src/test/java/ru/vsu/amm/java/config/test.properties
  app/G91/enokyan.gera/lab5/src/test/java/ru/vsu/amm/java/enums/CarBrand.java
  app/G91/enokyan.gera/lab5/src/test/java/ru/vsu/amm/java/service/BadTestConfigOne.java
  app/G91/enokyan.gera/lab5/src/test/java/ru/vsu/amm/java/service/BadTestConfigThree.java
  app/G91/enokyan.gera/lab5/src/test/java/ru/vsu/amm/java/service/BadTestConfigTwo.java
  app/G91/enokyan.gera/lab5/src/test/java/ru/vsu/amm/java/service/TestConfig.java
  settings.gradle.kts
Labels: ʕ·ᴥ·ʔ
